### ISSUE TITLE
bugs in scripts/setup-tpch-db

### ISSUE THREAD

**Issue by chen1yuan** [eyalroz/tpch-tools#5]
1. in setup-tpch-db:229:
`[[ ! -d "$data_generation_dir" ]] || die "Was requested ...."`
should be changed to
`[[ -d "$data_generation_dir" ]] || die "Was requested ...."`
The logic is: if data directory doesn't exist , then "die" statement should be executed.

2. in setup-tpch-db: 400:
`[[ -e $data_generation_dir ]] || die "..."`
When there is no file named "$data_generation_dir ", condition "[[ -e $data_generation_dir ]]" is false and the latter "die" statement is executed, which is not wanted.
Actually, the [[-e $data_generation_dir]] condition should be changed to [[ ! -e "$data_generation_dir" ]].

**Comment by eyalroz** [comment]
Thank you for reporting this; fixed...
